package com.contact.service.entity;

import java.util.Date;

public class PetOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.petId
     *
     * @mbg.generated
     */
    private Integer petid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.shipDate
     *
     * @mbg.generated
     */
    private Date shipdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.complete
     *
     * @mbg.generated
     */
    private byte[] complete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.id
     *
     * @return the value of pet_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.id
     *
     * @param id the value for pet_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.petId
     *
     * @return the value of pet_order.petId
     *
     * @mbg.generated
     */
    public Integer getPetid() {
        return petid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.petId
     *
     * @param petid the value for pet_order.petId
     *
     * @mbg.generated
     */
    public void setPetid(Integer petid) {
        this.petid = petid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.quantity
     *
     * @return the value of pet_order.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.quantity
     *
     * @param quantity the value for pet_order.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.shipDate
     *
     * @return the value of pet_order.shipDate
     *
     * @mbg.generated
     */
    public Date getShipdate() {
        return shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.shipDate
     *
     * @param shipdate the value for pet_order.shipDate
     *
     * @mbg.generated
     */
    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.status
     *
     * @return the value of pet_order.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.status
     *
     * @param status the value for pet_order.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.complete
     *
     * @return the value of pet_order.complete
     *
     * @mbg.generated
     */
    public byte[] getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.complete
     *
     * @param complete the value for pet_order.complete
     *
     * @mbg.generated
     */
    public void setComplete(byte[] complete) {
        this.complete = complete;
    }
}