package com.contact.service.dao;

import com.contact.service.entity.PetPet;
import java.util.List;

public interface PetPetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_pet
     *
     * @mbg.generated
     */
    int insert(PetPet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_pet
     *
     * @mbg.generated
     */
    List<PetPet> selectAll();
}