package com.contact.service.dao;

import com.contact.service.entity.PetTag;
import java.util.List;

public interface PetTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_tag
     *
     * @mbg.generated
     */
    int insert(PetTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_tag
     *
     * @mbg.generated
     */
    List<PetTag> selectAll();
}